language: perl
sudo: true
addons:
  apt:
    #sources:
    #  - ubuntugis/ubuntugis-unstable
    packages:
    - libgdal-dev
matrix:
  include:
    - perl: "5.20"
      env: BD_NO_GUI_TEST=1
    - perl: "5.22"
      env: BD_NO_GUI_TEST=1
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - export SPLIT_BUILD=0
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - sudo ./install_gdal.sh
install:
  - cpan-install --deps       # installs prereqs, including recommends
branches:
  except:
    - /^wip\//
    - /^blocked/
  only:
    - master
