language: perl
sudo: false
addons:
  apt:
    #sources:
    #  - ubuntugis/ubuntugis-unstable
    packages:
      #  not sure these are all needed now we build and cache gdal
    - libgdal-dev build-essential python-all-dev
matrix:
  include:
    - perl: "5.20.1"
      env:
        - gdal_version=1.11.2
        - geo_gdal_tar=Geo-GDAL-1.9921a.tar.gz
        - geo_gdal_dir=Geo-GDAL-1.9921
    - perl: "5.20.1"
      env:
        - gdal_version=2.0.0
        - geo_gdal_tar=Geo-GDAL-2.00003.tar.gz
        - geo_gdal_dir=Geo-GDAL-2.00003
    - perl: "5.22"
      env:
        - gdal_version=1.11.2
        - geo_gdal_tar=Geo-GDAL-1.9921a.tar.gz
        - geo_gdal_dir=Geo-GDAL-1.9921
    - perl: "5.22"
      env:
        - gdal_version=2.0.0
        - geo_gdal_tar=Geo-GDAL-2.00003.tar.gz
        - geo_gdal_dir=Geo-GDAL-2.00003
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  #- export SPLIT_BUILD=0
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - mkdir -p $HOME/gdal
  - export PATH=$HOME/gdal/bin:$PATH
  - which cpanm
  - cpanm --no-interactive --notest --skip-satisfied Task::Biodiverse::NoGUI
install:
  - startdir=`pwd`
  - which perl
  - gdalconfig=`find $HOME -name gdal-config -print`
  - echo $gdalconfig
  - if [ -n $gdalconfig ]; then wget http://download.osgeo.org/gdal/${gdal_version}/gdal-${gdal_version}.tar.gz; fi
  - if [ -n $gdalconfig ]; then tar -xzvf gdal-${gdal_version}.tar.gz; fi
  - if [ -n $gdalconfig ]; then cd gdal-${gdal_version} && ./configure --prefix=$HOME/gdal && make && make install; fi
  - if [ -n $gdalconfig ]; then cd -; fi
  - if [ -n $gdalconfig ]; then gdalconfig=`which gdal-config`; fi
  - ls -R ~/gdal
  - wget https://cpan.metacpan.org/authors/id/A/AJ/AJOLMA/${geo_gdal_tar}
  - tar -xzvf ${geo_gdal_tar}
  - cd ${geo_gdal_dir} && perl Makefile.PL --no-version-check --gdal-config=$gdalconfig && make && make test && make install && make clean
  - echo 'GDAL installed'
  - pwd
  - cd .. 
  - rm -r ${geo_gdal_dir}  #  avoid makefile confusion - might be handled by the make clean though
  - cd $startdir
  - perl -MGeo::GDAL -E'say "got Geo::GDAL"'
  - pwd
  #- cpan-install --deps       # installs prereqs, including recommends
branches:
  except:
    - /^wip\//
    - /^blocked/
  only:
    - master
cache:  #  need to work out how to use this across the matrix
  directories:
  - $HOME/gdal
