language: perl
sudo: false
addons:
  apt:
    #sources:
    #  - ubuntugis/ubuntugis-unstable
    packages:
      #  not sure these are all needed now we build and cache gdal
    - libgdal-dev build-essential python-all-dev
matrix:
  include:
    - perl: "5.20.1"
      env: BD_NO_GUI_TEST=1
    #- perl: "5.22"
    #  env: BD_NO_GUI_TEST=1
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  #- export SPLIT_BUILD=0
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  #- pwd
  #- ls -l
  #- mkdir ~/gdal
  - export PATH=$HOME/gdal/bin:$PATH
  #- sh ./install_gdal.sh
install:
  - which perl
  #- wget http://download.osgeo.org/gdal/1.11.2/gdal-1.11.2.tar.gz
  #- tar -xzvf gdal-1.11.2.tar.gz
  #- cd gdal-1.11.2 && ./configure --prefix=$HOME/gdal && make && make install
  - cd -
  #- which gdal-config
  - ls -R ~/gdal
  - wget https://cpan.metacpan.org/authors/id/A/AJ/AJOLMA/Geo-GDAL-1.9921a.tar.gz
  - tar -xzvf Geo-GDAL-1.9921a.tar.gz
  - cd Geo-GDAL-1.9921 && perl Makefile.PL --no-version-check --gdal-config=$HOME/gdal/bin/gdal-config && make && make test && make install
  - cd -
  - cpan-install --deps       # installs prereqs, including recommends
branches:
  except:
    - /^wip\//
    - /^blocked/
  only:
    - master
#cache:  #  need to work out how to use this across the matrix
#  directories:
#  - $HOME/gdal
